server:
  port: 8080
  servlet:
    context-path: /wx
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/girldb
    username: root
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
